name: Update Proxy List
on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:
jobs:
  build:
    runs-all-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run filter
        run: python filter.py
      - name: Commit and push changes
        run: |
          git config --global user.name "Actions Bot"
          git config --global user.email "bot@github.com"
          git add filtered_vless.txt
          git commit -m "Update list" || exit 0
          git push
